<a href="https://colab.research.google.com/github/kaisacht/Project1/blob/main/MLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from __future__ import print_function
 
from tensorflow import keras
import numpy as np
import pandas as pd

In [ ]:
np.random.seed(813306)

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving 20_day_TRAIN.txt to 20_day_TRAIN.txt


In [ ]:
def readucr(filename):
    data = np.loadtxt(filename, delimiter = ',')
    Y = data[:,0]
    X = data[:,1:]
    return X, Y

In [ ]:
x_train, y_train = readucr('20_day_TRAIN.txt')
x_test, y_test = readucr('20_day_TEST.txt')

In [ ]:
print(x_test,y_test)

[[ 29.17  29.03  28.87 ...  29.81  29.83  29.4 ]
 [ 29.44  29.45  29.53 ...  30.14  30.35  30.37]
 [ 30.13  29.41  29.22 ...  27.92  27.73  27.76]
 ...
 [275.84 272.38 276.61 ... 275.11 274.52 267.98]
 [263.85 260.66 261.33 ... 237.57 235.2  236.9 ]
 [234.5  234.73 234.41 ... 234.87 234.5  241.3 ]] [3. 3. 1. 3. 3. 3. 1. 3. 1. 3. 3. 3. 3. 1. 1. 1. 3. 3. 1. 1. 3. 3. 1. 1.
 1. 1. 1. 1. 3. 3. 3. 3. 3. 1. 3. 3. 3. 3. 3. 1. 3. 3. 3. 1. 1. 3. 1. 3.
 3. 3. 3. 3. 1. 1. 3. 1. 1. 3. 1. 3. 3. 1. 1. 3. 3. 3. 1. 1. 1. 3. 1. 3.
 3. 1. 1. 3. 1. 3. 3. 3. 3. 3. 1. 1. 1. 3. 3. 3. 1. 1. 3. 3. 3. 1. 3. 3.
 3. 3. 1. 3. 1. 1. 1. 1. 3. 3. 1. 1. 3. 1. 3. 3. 3. 3. 1. 1. 3. 3. 1. 1.
 3. 3. 1. 3. 3. 1. 3. 3. 3. 3. 3. 3. 1. 3. 1. 3. 3. 3. 3. 3. 3. 3. 3. 3.
 3. 3. 3. 1. 3. 1. 3. 1. 3. 3. 3. 3. 1. 3. 3. 1. 3. 3. 3. 3. 3. 3. 1. 3.
 3. 3. 3. 3. 3. 1. 1. 3. 3. 3. 1. 3. 3. 1. 3. 3. 3. 3. 1. 3. 3. 1. 1. 1.
 3. 1. 1. 1. 3. 1. 1. 3.]


In [ ]:
nb_epochs = 5000

In [ ]:
flist = ['Adiac']
for each in flist:
    fname = each
    x_train, y_train = readucr('20_day_TRAIN.txt')
    x_test, y_test = readucr('20_day_TEST.txt')
    nb_classes =len(np.unique(y_test))
    y_train = (y_train - y_train.min())/(y_train.max()-y_train.min())*(nb_classes-1)
    y_test = (y_test - y_test.min())/(y_test.max()-y_test.min())*(nb_classes-1)
    batch_size = min(x_train.shape[0]/10, 16)
    
    Y_train = keras.utils.to_categorical(y_train, nb_classes)
    Y_test = keras.utils.to_categorical(y_test, nb_classes)
     
    x_train_mean = x_train.mean()
    x_train_std = x_train.std()
    x_train = (x_train - x_train_mean)/(x_train_std)
     
   # x_test_min = np.min(x_test, axis = 1, keepdims=1)
   # x_test_max = np.max(x_test, axis = 1, keepdims=1)
    x_test = (x_test - x_train_mean)/(x_train_std)
     
    #x_train = x_train.reshape(x_train.shape + (1,))
    #x_test = x_test.reshape(x_test.shape + (1,))
    
    x = keras.layers.Input(x_train.shape[1:])
    y= keras.layers.Dropout(0.1)(x)
    y = keras.layers.Dense(500, activation='relu')(y)
    y = keras.layers.Dropout(0.2)(y)
    y = keras.layers.Dense(500, activation='relu')(y)
    y = keras.layers.Dropout(0.2)(y)
    y = keras.layers.Dense(500, activation = 'relu')(y)
    y = keras.layers.Dropout(0.3)(y)
    out = keras.layers.Dense(nb_classes, activation='softmax')(y)
     
    model = keras.models.Model(inputs=x, outputs=out)
     
    optimizer = keras.optimizers.Adadelta()    
    model.compile(loss='categorical_crossentropy',
                  optimizer=optimizer,
                  metrics=['accuracy'])
     
    reduce_lr = keras.callbacks.ReduceLROnPlateau(monitor = 'loss', factor=0.5,
                      patience=200, min_lr=0.1)
    
    hist = model.fit(x_train, Y_train, batch_size=batch_size, epochs=nb_epochs,
              verbose=1, validation_data=(x_test, Y_test), 
                #callbacks = [TestCallback((x_train, Y_train)), reduce_lr, keras.callbacks.TensorBoard(log_dir='./log'+fname, histogram_freq=1)])
                 callbacks=[reduce_lr])
    
    #Print the testing results which has the lowest training loss.


Kết quả truyền trực tuyến bị cắt bớt đến 5000 dòng cuối.
13/13 [==============================] - 0s 23ms/step - loss: 0.6091 - accuracy: 0.6634 - val_loss: 0.4805 - val_accuracy: 0.8250 - lr: 0.0010
Epoch 2502/5000
13/13 [==============================] - 0s 22ms/step - loss: 0.6262 - accuracy: 0.6535 - val_loss: 0.4805 - val_accuracy: 0.8300 - lr: 0.0010
Epoch 2503/5000
13/13 [==============================] - 0s 22ms/step - loss: 0.6219 - accuracy: 0.6931 - val_loss: 0.4804 - val_accuracy: 0.8250 - lr: 0.0010
Epoch 2504/5000
13/13 [==============================] - 0s 21ms/step - loss: 0.6329 - accuracy: 0.6683 - val_loss: 0.4803 - val_accuracy: 0.8300 - lr: 0.0010
Epoch 2505/5000
13/13 [==============================] - 0s 23ms/step - loss: 0.6214 - accuracy: 0.6931 - val_loss: 0.4805 - val_accuracy: 0.8300 - lr: 0.0010
Epoch 2506/5000
13/13 [==============================] - 0s 22ms/step - loss: 0.6064 - accuracy: 0.6931 - val_loss: 0.4807 - val_accuracy: 0.8300 - lr: 0.0010
Epoch

In [ ]:
    log = pd.DataFrame(hist.history)
    print(log)

          loss  accuracy  val_loss  val_accuracy     lr
0     0.706135  0.509901  0.680493         0.795  0.001
1     0.686857  0.514852  0.677754         0.810  0.001
2     0.683707  0.564356  0.675518         0.800  0.001
3     0.689624  0.608911  0.673230         0.755  0.001
4     0.685905  0.500000  0.671986         0.725  0.001
...        ...       ...       ...           ...    ...
4995  0.653075  0.638614  0.436272         0.880  0.001
4996  0.558613  0.732673  0.434396         0.875  0.001
4997  0.589097  0.688119  0.433942         0.870  0.001
4998  0.611498  0.663366  0.433289         0.870  0.001
4999  0.613729  0.693069  0.433179         0.870  0.001

[5000 rows x 5 columns]


In [ ]:
log_np = np.array(log)
log_np
min_index = (np.argmin(log_np, axis=0))
print(log_np[min_index[0]])

[0.53894025 0.73762375 0.43759668 0.85500002 0.001     ]
